server:
  port: 9135

dgraph:
  host: 162.105.88.139
  port: 9084

spring:
  data:
    mongodb:
      host: 162.105.88.139
      port: 27032
      database: relation
      username: rootxyx
      password: woxnsk!